In [3]:
!dir

 ’®¬ ў гбва®©б⢥ C Ё¬ҐҐв ¬ҐвЄг Acer
 ‘ҐаЁ©­л© ­®¬Ґа ⮬ : 0A91-591B

 ‘®¤Ґа¦Ё¬®Ґ Ї ЇЄЁ C:\Users\qu4n7\Desktop\python_data_science

13.02.2019  09:07    <DIR>          .
13.02.2019  09:07    <DIR>          ..
13.02.2019  09:07    <DIR>          .ipynb_checkpoints
13.02.2019  09:07                72 lesson_1.ipynb
               1 д ©«®ў             72 Ў ©в
               3 Ї Ї®Є  23я296я053я248 Ў ©в бў®Ў®¤­®


In [5]:
# shift + tab for more info
print()

In [6]:
%lsmagic # % действует на 1 строку кода, $$ - на всю ячейку

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%

In [7]:
%run # <name.py> # запускает файл с расширением .py
%load # <name.py> # выгружает из файла с расширением .py в ячейку

UsageError: Cell magic `%%lsmagic` not found (But line magic `%lsmagic` exists, did you mean that instead?).


In [2]:
import numpy as np

#### 1D

In [11]:
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.array(a, dtype = float)

In [17]:
c = [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.9]
c

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.9]

In [19]:
d = np.array(c, dtype = int)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
e = np.array(d, dtype = str)
e

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U11')

In [22]:
e.ndim

1

In [23]:
e.shape

(10,)

#### 2D

In [4]:
f = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
             [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 
             [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
f.size

30

In [46]:
f[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
f[1][2]

12

In [5]:
f[1,1]

11

In [7]:
f[0, -1]

9

In [12]:
f[0:2, 1:3] # [row:rows, column:column]

array([[ 1,  2],
       [11, 12]])

In [14]:
g = f[1:, 2:] # матрица g - отажение матрицы f
g

array([[12, 13, 14, 15, 16, 17, 18, 19],
       [22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
g[1, 3] = 1000
g

array([[  12,   13,   14,   15,   16,   17,   18,   19],
       [  22,   23,   24, 1000,   26,   27,   28,   29]])

In [16]:
f # в исходной матрицы проведутся измения их матриы отражения

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24, 1000,   26,   27,   28,   29]])

In [19]:
h = f[0:, 3:].copy()
h

array([[   3,    4,    5,    6,    7,    8,    9],
       [  13,   14,   15,   16,   17,   18,   19],
       [  23,   24, 1000,   26,   27,   28,   29]])

In [21]:
h[1,3] = 1000
h

array([[   3,    4,    5,    6,    7,    8,    9],
       [  13,   14,   15, 1000,   17,   18,   19],
       [  23,   24, 1000,   26,   27,   28,   29]])

In [22]:
f

array([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24, 1000,   26,   27,   28,   29]])

#### работа с векторами

In [24]:
import numpy as np

In [30]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])

In [31]:
print(a.size, b.size)

5 5


In [32]:
a + b

array([ 5,  7,  9, 11, 13])

In [29]:
# check the difference
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

In [35]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])

In [36]:
a - b

array([-5, -5, -5, -5, -5])

In [38]:
c = np.subtract(a, b)
c

array([-5, -5, -5, -5, -5])

In [40]:
a = np.array([0, 1, 2, 3, 4])
d = a * 10
d

array([ 0, 10, 20, 30, 40])

In [42]:
# chekc the difference
x1 = [0, 1, 2, 3, 4] * 2
x1

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [43]:
a.dot(-0.5)

array([ 0. , -0.5, -1. , -1.5, -2. ])

In [44]:
np.dot(a,2)

array([0, 2, 4, 6, 8])

In [45]:
np.multiply(a, 2)

array([0, 2, 4, 6, 8])

In [46]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 7, 8, 9])

In [48]:
sp = a[0]*b[0] + a[1]*b[1] + a[2]*b[2] + a[3]*b[3] + a[4]*b[4]
sp

80

In [49]:
a @ b

80

In [50]:
np.dot(a, b)

80

In [52]:
A = np.array([[0, 1],
             [2, 3],
             [4, 5]])
B = np.array([[11, 15],
             [22, 33],
             [41, 51]])

In [53]:
print(A.shape, B.shape)

(3, 2) (3, 2)


In [54]:
A + B

array([[11, 16],
       [24, 36],
       [45, 56]])

In [55]:
np.add(A, B)

array([[11, 16],
       [24, 36],
       [45, 56]])

In [56]:
A - B

array([[-11, -14],
       [-20, -30],
       [-37, -46]])

In [57]:
np.subtract(A, B)

array([[-11, -14],
       [-20, -30],
       [-37, -46]])

#### работа с матрицами

In [1]:
import numpy as np

In [2]:
X1 = np.array([[1, 2],
              [3, 4],
              [5, 0]])
X2 = np.array([[11, 12, 13, 14],
              [32, 24, 54, 23]])

In [3]:
X1.shape[1] == X2.shape[0]

True

In [4]:
print(X1.shape, X2.shape)

(3, 2) (2, 4)


In [5]:
Z = np.dot(X1, X2)
Z

array([[ 75,  60, 121,  60],
       [161, 132, 255, 134],
       [ 55,  60,  65,  70]])

In [6]:
Z.shape

(3, 4)

In [10]:
 X1[0, 0] * X2[0, 0] + X1[0, 1]* X2[1, 0]

75

In [19]:
D = np.array([[12, 21],
             [32, 23]])

In [20]:
D_sq = np.dot(D, D)
D_sq

array([[ 816,  735],
       [1120, 1201]])

In [25]:
D_squ = np.linalg.matrix_power(D, 7)
D_squ

array([[1949362528, 1954145497],
       [-499132768, -503915737]])

In [27]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
X1_t = X1.T
X1_t

array([[1, 3, 5],
       [2, 4, 0]])

In [31]:
np.linalg.det(D)

-396.0

In [33]:
np.linalg.matrix_rank(I)

3

In [37]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.05808081,  0.0530303 ],
       [ 0.08080808, -0.03030303]])

#### работа с массивами 

In [39]:
import numpy as np

In [42]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
b = np.ones((4,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.arange(1, 101, 4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [52]:
np.arange(101, 1, -4) # обратная последовательность

array([101,  97,  93,  89,  85,  81,  77,  73,  69,  65,  61,  57,  53,
        49,  45,  41,  37,  33,  29,  25,  21,  17,  13,   9,   5])

In [56]:
np.linspace(1, 2, 100)

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [60]:
np.logspace(0, 1, 2)

array([ 1., 10.])

In [63]:
np.random.sample((3, 5))

array([[0.08313746, 0.99131441, 0.48385266, 0.54512297, 0.07682581],
       [0.84203114, 0.8697739 , 0.61778592, 0.31176262, 0.57879433],
       [0.52882238, 0.22814679, 0.07756965, 0.83453675, 0.75511794]])

In [66]:
a = np.arange(1, 13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
np.reshape(a, (4, -1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
np.reshape(a, (-1, 3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
b = a.resize(3, 4)
b

In [80]:
a = np.random.randint(0, 20, 10)
a

array([ 8,  3,  7, 15, 15,  4,  9, 18,  7,  7])

In [82]:
a[a > 10]

array([15, 15, 18])

In [84]:
a[(a > 10) & (a < 17)]

array([15, 15])

In [85]:
a[(a > 15) | (a < 5)]

array([ 3,  4, 18])

In [86]:
np.where(a > 10) # показывает индексы только

(array([3, 4, 7], dtype=int64),)

In [87]:
a = [1, 3, 5, 7]
b = [2, 4, 6, 8]
np.where([True, False, True, False], a, b)

array([1, 4, 5, 8])

In [89]:
a = np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [91]:
a.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int64)

In [93]:
a[a[:, 0].argsort(), :]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a[[:, 0]]

In [95]:
a = np.random.randint(0, 100, [5, 8])
a

array([[61, 35,  8, 23, 63, 70, 67,  4],
       [ 3, 66, 43, 47, 61, 92, 27, 47],
       [16, 50, 96,  8, 62, 21, 34, 46],
       [66, 45, 41, 76, 95, 32, 13, 70],
       [20, 48, 62, 97, 99, 85,  2, 58]])