In [2]:
import numpy as np

In [5]:
product_names = np.array(['хлеб', 'молоко', 'творог'])
product_names

array(['хлеб', 'молоко', 'творог'], dtype='<U6')

In [8]:
price=np.array([30, 80, 60])
price

numpy.ndarray

In [10]:
names = np.array(['Bob', 'Alice', 'Joe'])
names

array(['Bob', 'Alice', 'Joe'], dtype='<U5')

In [13]:
# в строках - покупки покупателей, в столбцах - продукты (хлеб, молоко, творог)
history = np.array([[1, 2, 1], 
                    [2, 3, 0], 
                    [0, 1, 4]])
history

array([[1, 2, 1],
       [2, 3, 0],
       [0, 1, 4]])

In [16]:
history[0] #bob
#history[0,:]

array([1, 2, 1])

In [19]:
history[names=='Bob'] # NICE SEQUENCE

array([[1, 2, 1]])

In [26]:
history[names=='Bob', product_names=='хлеб']

array([1])

##### broadcasting

In [29]:
sum_history = history * price
sum_history

array([[ 30, 160,  60],
       [ 60, 240,   0],
       [  0,  80, 240]])

In [30]:
sum_history[names=='Bob']

array([[ 30, 160,  60]])

##### aggregation

In [35]:
sum_history.sum(axis=0)

array([ 90, 480, 300])

In [37]:
sum_history.sum(axis=1)

array([250, 300, 320])

In [38]:
sum_history.sum(axis=1)[product_names=='творог']

array([320])

In [40]:
# mean, min, max by products
print(f'mean: {sum_history.mean(axis=0)}')
print(f'max: {sum_history.max(axis=0)}')
print(f'min: {sum_history.min(axis=0)}')

mean: [ 30. 160. 100.]
max: [ 60 240 240]
min: [ 0 80  0]


##### matrix join

In [43]:
features = np.array(['Rooms', 'Square', 'KitchenSquare'])
features

array(['Rooms', 'Square', 'KitchenSquare'], dtype='<U13')

In [44]:
flat_id = np.array([123, 124, 125, 180])

In [42]:
flats = np.array([[1, 35, 8], 
                  [1, 38, 10], 
                  [2, 45, 11], 
                  [3, 65, 12]])

In [46]:
price = np.array([3.5, 3.7, 5.5, 7.2])

In [48]:
price.ndim

1

In [49]:
price.shape

(4,)

In [52]:
price = price.reshape((-1,1))
price

array([[3.5],
       [3.7],
       [5.5],
       [7.2]])

In [76]:
flats2 = np.hstack([flats, price])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2]])

In [56]:
new_flat = np.array([4, 75, 15, 12.5])
new_flat

array([ 4. , 75. , 15. , 12.5])

In [77]:
flats2 = np.vstack([flats2, new_flat])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2],
       [ 4. , 75. , 15. , 12.5]])

In [78]:
flats2[:,-1] # only prices

array([ 3.5,  3.7,  5.5,  7.2, 12.5])

In [79]:
flats2[:,-1].sum()

32.4

In [80]:
flats2[:,-1].mean()

6.4799999999999995

In [83]:
np.median(flats2[:,-1])

5.5

In [87]:
features2 = np.hstack([features, 'Price'])

In [88]:
features2

array(['Rooms', 'Square', 'KitchenSquare', 'Price'], dtype='<U13')

In [91]:
flats2[:, features2=='Rooms']

array([[1.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [94]:
flats2[:, features2=='Rooms'].mean()

2.2

In [95]:
new_flat2 = np.array([7, 350, 30, 57.5])

In [96]:
flats3 = np.vstack([flats2[:1,:], new_flat2, flats2[1:,:]])

In [97]:
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 38. , 10. ,  3.7],
       [ 2. , 45. , 11. ,  5.5],
       [ 3. , 65. , 12. ,  7.2],
       [ 4. , 75. , 15. , 12.5]])

In [98]:
flats3

array([[  1. ,  35. ,   8. ,   3.5],
       [  7. , 350. ,  30. ,  57.5],
       [  1. ,  38. ,  10. ,   3.7],
       [  2. ,  45. ,  11. ,   5.5],
       [  3. ,  65. ,  12. ,   7.2],
       [  4. ,  75. ,  15. ,  12.5]])

In [99]:
a = np.array([1, 3, np.nan])
a

array([ 1.,  3., nan])